name: Integration

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  integration_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - shell: bash
        run: |
          npm ci
      - shell: bash
        run: |
          npm ci --prefix ./projects/test/integration
      - shell: bash
        run: |
          npm run integration --prefix ./projects/test/integration
      - shell: bash
        run: |
          npm run build --prefix ./projects/test/integration
      - shell: bash
        run: |
          npm run generate --prefix ./projects/test/integration
      - shell: bash
        run: |
          npm run test --prefix ./projects/test/integration
    