name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version  (ie 1.1.1)'
        required: true

jobs:        
  build_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
            token: ${{ secrets.TEST_RECORDER_ACCESS_KEY }}
      - run: ./projects/extension/scripts/validate_version.js ${{ github.event.inputs.version }}
      - run: |
          git config user.name malykhin
          git config user.email malykhin@ukr.net
      - run: npm version ${{ github.event.inputs.version }}
      - run: git push origin master
      - run: |
          git checkout -b release/v${{ github.event.inputs.version }}
          git push origin release/v${{ github.event.inputs.version }}


